In [ ]:
Broadcasting Rules
Broadcasting is possible if the following cases are satisfied.

1.The smaller dimension array can be appended with '1' in its shape.
2.Size of each output dimension is the maximum of the input sizes in the dimension.
3.An input can be used in the calculation if its size in a particular dimension matches the output size or its value is exactly 1.
4.If the input size is 1, then the first data entry is used for the calculation along the dimension.


    
Broadcasting can be applied to the arrays if the following rules are satisfied.

1.All the input arrays have the same shape.
2.Arrays have the same number of dimensions, and the length of each dimension is either a common length or 1.
3.Array with the fewer dimension can be appended with '1' in its shape.


In [ ]:
# Example 1

x.shape == ( 2, 3 )

y.shape == ( 2, 3 ) # compatible
y.shape == ( 2, 1 ) # compatible
y.shape == ( 1, 3 ) # compatible
y.shape == ( 3, ) #(1, 3) compatible

#NOT compatibles

y.shape == ( 3, 2 ) # NOT compatible
y.shape == ( 2, ) # (1, 2) NOT compatible

In [ ]:
# Example 2


x.shape == ( 1000, 250, 250, 250 )

y.shape == ( 1000, 250, 250, 250 ) # compatible
y.shape == ( 1000, 1, 250, 250 ) # compatible
y.shape == ( 1000, 1, 1, 250 ) # compatible
y.shape == (250, 250, 250 ) # (1, 250, 250, 250) compatible
y.shape == (250, 1 ) # (1, 1, 250, 1) compatible

# in-compatible

y.shape == ( 1000, 250, 250 ) # (1, 1000, 250, 250) NOT compatible

In [1]:
# Examples
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

print(a.shape)
print(b.shape)
print(a + b)

(4,)
(4,)
[2 4 6 8]


In [2]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.shape)
print(a)

b = np.array([1,2,3])
print(b.shape)
print(b)

c = np.array([10,20])
print(c.shape)
print(c)

#print(a + b) #can't broadcast since (3,2) and (1,3) are incompatible shapes
print("Addition of a and c")
print(a + c)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3,)
[1 2 3]
(2,)
[10 20]
Addition of a and c
[[11 22]
 [13 24]
 [15 26]]


In [3]:
a = np.array([1,2,3])
b = np.array([[1],[2],[3]])

print(a.shape)
print(a)
print()
print(b.shape)
print(b)
print()
print(a + b)

(3,)
[1 2 3]

(3, 1)
[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]
